title: Elizaveta's page with jekyll 
author: ElizavetaOlar
email: elizaveta.olar@daimler.com
description: > # this means to ignore newlines until "baseurl:"
 How to create a github page with jekyll
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
